### ISSUE TITLE
Sportowa-SportsBay: Kodi cannot play basketball links neither NBA TV on Live Channels

### ISSUE THREAD

**Issue by galex3125** [mbebe/blomqvist#369]
Hi @mbebe,

This past couple days Kodi cannot play any of the Basketball links resolved by SportsBay.

In addition, Kodi cannot play the NBA TV channel on the "Live Channels: Sportsbay"

Can you please take a look on this when you have time?

Thank you so much!

**Comment by mbebe** [comment]
Update is available. New ver.: 2.0.1
I hope it's fixed now.

**Comment by galex3125** [comment]
Thank you so much for the update!

Next NBA playoff game is this weekend, so I'll let you know then.

Live Channels: Sportsbay: NBA TV still not working on Kodi.

**Comment by mbebe** [comment]
Please check this version, and try to watch NBA TV.
[plugin.video.PLsportowo-2.0.2.zip](https://github.com/mbebe/blomqvist/files/5232904/plugin.video.PLsportowo-2.0.2.zip)

**Comment by sviet2k** [comment]
I just tested it. It's working for me. 👍

**Comment by galex3125** [comment]
NBA TV is working now with the 2.0.2 update.

There's a playoff game in a few hours, so I will let you know later on tonight if the game link is also fixed.

Thanks again!

**Comment by galex3125** [comment]
All is working now using the 2.0.3 update.

Thank you so much again for the fix!

**Comment by galex3125** [comment]
Hi @mbebe,

The link to the Laker (Western Conference) playoff games is not working again today. These games are shown on TNT channel in the US.
