### ISSUE TITLE
Fmovies and MyCloud not working

### ISSUE THREAD

**Issue by theface78** [mbebe/blomqvist#776]
When streaming from MyCloud Kodi, there's always an error lately and the stream doesn't start. If trying the same video on the website, it streams from MyCloud without problems. So there cannot be any problem with MyCloud in general, it has to have something to do with Kodi or the Fmovies addon. Does anyone have the same experience?

**Comment by theface78** [comment]
![IMG_20220520_194754](https://user-images.githubusercontent.com/85312482/169583962-c13255ea-7b8f-4be2-8d37-18bbcf4006bc.jpg)

**Comment by mbebe** [comment]
Fixed in new version 1.11.

**Comment by theface78** [comment]
> Fixed in new version 1.11.

Excellent, it's working again! Well done and thank you for your amazing work!

**Comment by crak3rjack** [comment]
@theface78 McCloud is fixed in 1.11 as seen in the picture... maybe some won't work... there's 2 more options working fine!
![Screenshot_20220522-085306_colussus-194](https://user-images.githubusercontent.com/59179646/169696168-93132e0b-df42-4b02-ae39-c2c69c9dd653.jpg)

**Comment by theface78** [comment]
> @theface78 McCloud is fixed in 1.11 as seen in the picture... maybe some won't work... there's 2 more options working fine! ![Screenshot_20220522-085306_colussus-194](https://user-images.githubusercontent.com/59179646/169696168-93132e0b-df42-4b02-ae39-c2c69c9dd653.jpg)

Sorry, if three servers work on the website but the same servers except one don't work in Kodi, it's obviously not fully fixed or there's another error additionally.

**Comment by crak3rjack** [comment]
@theface78 It's working... what's happening is that all hosts server change code constantly because they know people like Kodi "addons" are using there links, meaning a increase in there bandwidth which means extra $$$ if they have upgrade... and also websites keep changing too trying to block people like Kodi "addons"✌

**Comment by theface78** [comment]
The problem is back, same goes for Vidstream. Sure, there are usually four options, sadly the only reliable one is MyCloud. It's impossible to watch "Barry" right now for example, since only MyCloud and Vidstream are working. It would be great if that could be fixed! Thanks!

**Comment by theface78** [comment]
> Fixed in new version 1.11.

It would be great if you could take a look again, thank you so much!

**Comment by MrDhaakkan** [comment]
Hey bro, i just installed the fmovie.to add a few weeks ago and it was working fine. now when i go to the movies it just say no link available. for every single movie and Tv shows. can you take a look into it?
